"""History compaction (Plan I P0.4).

When the chat history exceeds a token budget, we compact older turns
into a single summary message while preserving the recent turns. The
summary is generated by the active model via a one-shot call.

This mirrors Hermes' ``summarize_history`` analog (Hermes uses the
same provider that was used in the running agent so the summary has
the right tone).
"""

from __future__ import annotations

from typing import Any

from eaccode.token_counter import (
    estimate_history_tokens,
    estimate_message_tokens,
)


def should_compact(
    messages: list[dict[str, Any]],
    tool_definitions: list[dict[str, Any]],
    context_window_tokens: int,
    threshold: float = 0.8,
) -> bool:
    """True when ``messages + tool_definitions`` exceeds ``threshold`` of context."""
    if context_window_tokens <= 0:
        return False
    used = estimate_history_tokens(messages) + (
        sum(_tool_size(t) for t in tool_definitions) // 4
    )
    return used > context_window_tokens * threshold


def _tool_size(tool: dict[str, Any]) -> int:
    """Estimate bytes/4 (rough token count) of a tool definition."""
    return (len(str(tool.get("description", ""))) + len(str(tool))) // 4


def select_compaction_window(
    messages: list[dict[str, Any]],
    keep_recent: int = 4,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Split messages into (older_to_compact, recent_to_keep).

    The split keeps the ``keep_recent`` most recent messages verbatim
    and marks everything before for compaction. System messages are
    always preserved verbatim.
    """
    if len(messages) <= keep_recent + 1:
        return [], list(messages)

    # Find the first system message boundary - everything before that is
    # also a "system" message that we keep.
    system_idx = 0
    for i, msg in enumerate(messages):
        if msg.get("role") == "system":
            system_idx = i + 1

    head = messages[:system_idx]
    body = messages[system_idx:]

    if len(body) <= keep_recent:
        return [], list(messages)

    to_compact = body[:-keep_recent]
    to_keep = head + body[-keep_recent:]
    return to_compact, to_keep


def format_messages_for_summary(messages: list[dict[str, Any]]) -> str:
    """Render messages as a compact transcript for the model to summarize."""
    parts: list[str] = []
    for msg in messages:
        role = msg.get("role", "?")
        content = msg.get("content", "")
        if isinstance(content, list):
            content = " ".join(
                str(p.get("text", "")) if isinstance(p, dict) else str(p)
                for p in content
            )
        tool_calls = msg.get("tool_calls") or []
        tc_summary = ""
        if tool_calls:
            tc_summary = " [tool_calls: " + ", ".join(
                str(tc.get("function", {}).get("name", "?"))
                for tc in tool_calls
            ) + "]"
        parts.append(f"[{role}]{tc_summary} {content}")
    return "\n".join(parts)


def summarize_prompt(transcript: str) -> list[dict[str, Any]]:
    """Build the prompt for the model to summarize the transcript."""
    return [
        {
            "role": "user",
            "content": (
                "Summarize the following conversation in 3-5 sentences. "
                "Preserve: (a) the user's stated goal, (b) key decisions "
                "made, (c) any facts or constraints that must not be lost. "
                "Use concise prose. No preamble.\n\n"
                f"--- TRANSCRIPT ---\n{transcript}\n--- END ---"
            ),
        }
    ]


def make_summary_message(summary_text: str) -> dict[str, Any]:
    """Wrap a summary string into a system message that fits the history."""
    return {
        "role": "system",
        "content": (
            "Earlier conversation summary (compacted to fit context window): "
            + summary_text.strip()
        ),
    }


__all__ = [
    "should_compact",
    "select_compaction_window",
    "format_messages_for_summary",
    "summarize_prompt",
    "make_summary_message",
]